---
  - name: Init Swarm Master
    hosts: masters
    gather_facts: False
    remote_user: ec2-user
    tasks:
      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Master Token
        command: docker swarm join-token manager -q
        register: master_token

      - name: Show Master Token
        debug: var=master_token.stdout
